### ISSUE TITLE
lightspeed support

### ISSUE THREAD

**Issue by max397574** [Weissle/easy-action#2]
would it be possible to add support for lightspeed.nvim?

**Comment by Weissle** [comment]
It should be easy to add basic support for lightspeed.nvim.
The config is similar to the `leap` part.
You may try the below config but I didn't test it.
```lua
require("easy-action").setup({
  jump_provider = "lightspeed",
  jump_provider_config = {
     lightspeed = {
       action_select = {
           default = function()
               require'lightspeed'.sx:go({ ['cross-window?'] = true })
           end
       }
    }
})
```
reference:
https://github.com/ggandor/lightspeed.nvim/blob/main/plugin/init.lua#L8
