### ISSUE TITLE
svart.nvim support

### ISSUE THREAD

**Issue by Piotr1215** [Weissle/easy-action#3]
Could you please add support for `svart.nvim` https://gitlab.com/madyanov/svart.nvim

**Comment by Weissle** [comment]
You may check the section `Use other jump plugins` in [README.md](https://github.com/Weissle/easy-action/blob/main/README.md).
Supporting all of these plugins by myself is time-consuming.

**Comment by Piotr1215** [comment]
Thank you, I'll look into the custom config.
